/*
 * JS for Home generated by Exadel Tiggzi
 *
 * Created on: Thursday, October 11, 2012, 07:08:19 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '72bec4fc-27f6-4fca-9f3d-8ce445f38f34';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
var WACPaymentOAuth2Context = new WACPaymentO2SecurityContext({
    'api_key': ''
});
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
var WACPaymentSettings = {
    "application_id": "wac-2e77619a-ccd3-44f7-b9c4-2baaea7d948e",
    "client_id": "wac-a24874833b25ba2df799c0fe3bf49369a3f77d25",
    "shared_secret": "9ac9beb46a9df8c96567eaf48f44e97ccd8aedbd",
    "redirect_uri": "https://gateway.wacapps.net/redirect/2b3b38c5-6877-48c0-9802-21f4279e17a1",
    "developer_name": "Omar Daniels",
    "authorize_uri": "https://api.wacapps.net//2/oauth/authorize",
    "product_uri": "https://api.wacapps.net/products",
    "spoof_ip": ""
}
/*************************
 *      SERVICES          *
 *************************/
var WACPaymentQueryProducts = new Tiggr.RestService({
    'url': '{product_uri}/{application_id}/{item_id}',
    'dataType': 'json',
    'type': 'get',
});
var WACPaymentCharge = new Tiggr.RestService({
    'url': 'https://api.wacapps.net//2/payment/acr:Authorization/transactions/amount',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
    'securityContext': WACPaymentOAuth2Context
});
var WACPaymentItemsProperties = new Tiggr.RestService({
    'url': 'http://tiggzi.com',
    'dataType': 'json',
    'type': 'get',
    'echo': {
        "results": [{
            "id": "wac-a0552795-c384-4005-92ea-4ceacdee0e03",
            "image": "https://wacoperatorimages.s3.amazonaws.com/b2c6647a021118685634262b6eb78e08",
            "name": "Audio Cambridge"
        }, {
            "id": "wac-c422851b-0140-47da-8079-27d382898428",
            "image": "https://wacoperatorimages.s3.amazonaws.com/49fb4f030abb3f598866898cc56ade74",
            "name": "Catalan Dictionary"
        }, {
            "id": "wac-09838a8d-eba5-49d9-a999-38ac9612046e",
            "image": "https://wacoperatorimages.s3.amazonaws.com/89cfffeff2b4111fdec193aab7f938c0",
            "name": "Russian Dictionary"
        }, {
            "id": "wac-5b89df28-aaf1-4b47-9142-c4731ea2525e",
            "image": "https://wacoperatorimages.s3.amazonaws.com/0ed759e1d1c2d3c2eac8dd46198cdfb1",
            "name": "Merriam-Webster"
        }]
    }
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "FreeBeats",
    "location": "FreeBeats.html"
}, {
    "name": "WACPaymentSplash",
    "location": "WACPaymentSplash.html"
}, {
    "name": "WACPaymentAuthorization",
    "location": "WACPaymentAuthorization.html"
}, {
    "name": "WACPaymentDetail",
    "location": "WACPaymentDetail.html"
}, {
    "name": "WACPaymentMain",
    "location": "WACPaymentMain.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Beatsforsale",
    "location": "Beatsforsale.html"
}];
j_106_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage2': 'j_110',
        'mobilebutton1': 'j_111',
        'mobilebutton2': 'j_112',
        'mobilebutton3': 'j_113',
        'mobilebutton4': 'j_114'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_106';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_106_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_106';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_CD07_onLoad = j_106_onLoad = function() {
        screen_CD07_elementsExtraJS();
        j_106_windowEvents();
        screen_CD07_elementsEvents();
    }
    // screen window events
    screen_CD07_windowEvents = j_106_windowEvents = function() {
        $('#j_106').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_CD07_elementsExtraJS = j_106_elementsExtraJS = function() {
        // screen (screen-CD07) extra code
    }
    // screen elements handler
    screen_CD07_elementsEvents = j_106_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_109 [name="mobileimage2"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_109 [name="mobilebutton1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('FreeBeats', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_109 [name="mobilebutton2"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Beatsforsale', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_106").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_106_beforeshow();
    });
    if (runBeforeShow) {
        j_106_beforeshow();
    } else {
        j_106_onLoad();
    }
}
$("#j_106").die("pageinit").live("pageinit", function(event, ui) {
    j_106_js();
});