/*
 * JS for WACPaymentDetail generated by Exadel Tiggzi
 *
 * Created on: Thursday, October 11, 2012, 07:08:19 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '72bec4fc-27f6-4fca-9f3d-8ce445f38f34';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
var WACPaymentOAuth2Context = new WACPaymentO2SecurityContext({
    'api_key': ''
});
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
var WACPaymentSettings = {
    "application_id": "wac-2e77619a-ccd3-44f7-b9c4-2baaea7d948e",
    "client_id": "wac-a24874833b25ba2df799c0fe3bf49369a3f77d25",
    "shared_secret": "9ac9beb46a9df8c96567eaf48f44e97ccd8aedbd",
    "redirect_uri": "https://gateway.wacapps.net/redirect/2b3b38c5-6877-48c0-9802-21f4279e17a1",
    "developer_name": "Omar Daniels",
    "authorize_uri": "https://api.wacapps.net//2/oauth/authorize",
    "product_uri": "https://api.wacapps.net/products",
    "spoof_ip": ""
}
/*************************
 *      SERVICES          *
 *************************/
var WACPaymentQueryProducts = new Tiggr.RestService({
    'url': '{product_uri}/{application_id}/{item_id}',
    'dataType': 'json',
    'type': 'get',
});
var WACPaymentCharge = new Tiggr.RestService({
    'url': 'https://api.wacapps.net//2/payment/acr:Authorization/transactions/amount',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/x-www-form-urlencoded',
    'securityContext': WACPaymentOAuth2Context
});
var WACPaymentItemsProperties = new Tiggr.RestService({
    'url': 'http://tiggzi.com',
    'dataType': 'json',
    'type': 'get',
    'echo': {
        "results": [{
            "id": "wac-a0552795-c384-4005-92ea-4ceacdee0e03",
            "image": "https://wacoperatorimages.s3.amazonaws.com/b2c6647a021118685634262b6eb78e08",
            "name": "Audio Cambridge"
        }, {
            "id": "wac-c422851b-0140-47da-8079-27d382898428",
            "image": "https://wacoperatorimages.s3.amazonaws.com/49fb4f030abb3f598866898cc56ade74",
            "name": "Catalan Dictionary"
        }, {
            "id": "wac-09838a8d-eba5-49d9-a999-38ac9612046e",
            "image": "https://wacoperatorimages.s3.amazonaws.com/89cfffeff2b4111fdec193aab7f938c0",
            "name": "Russian Dictionary"
        }, {
            "id": "wac-5b89df28-aaf1-4b47-9142-c4731ea2525e",
            "image": "https://wacoperatorimages.s3.amazonaws.com/0ed759e1d1c2d3c2eac8dd46198cdfb1",
            "name": "Merriam-Webster"
        }]
    }
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "FreeBeats",
    "location": "FreeBeats.html"
}, {
    "name": "WACPaymentSplash",
    "location": "WACPaymentSplash.html"
}, {
    "name": "WACPaymentAuthorization",
    "location": "WACPaymentAuthorization.html"
}, {
    "name": "WACPaymentDetail",
    "location": "WACPaymentDetail.html"
}, {
    "name": "WACPaymentMain",
    "location": "WACPaymentMain.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Beatsforsale",
    "location": "Beatsforsale.html"
}];
j_53_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'itemImageLarge': 'j_57',
        'mobilebutton5': 'j_58',
        'mobilegrid2': 'j_59',
        'mobilegridcell4': 'j_60',
        'mobilelabel10': 'j_61',
        'mobilegridcell5': 'j_62',
        'product_id_label': 'j_63',
        'mobilegridcell6': 'j_64',
        'mobilelabel11': 'j_65',
        'mobilegridcell7': 'j_66',
        'product_descr_label': 'j_67',
        'mobilegridcell8': 'j_68',
        'mobilelabel12': 'j_69',
        'mobilegridcell9': 'j_70',
        'price_label': 'j_71',
        'mobilegridcell10': 'j_72',
        'mobilelabel13': 'j_73',
        'mobilegridcell11': 'j_74',
        'currency_label': 'j_75',
        'mobilegridcell12': 'j_76',
        'mobilelabel14': 'j_77',
        'mobilegridcell13': 'j_78',
        'billing_label': 'j_79',
        'mobilegridcell14': 'j_80',
        'mobilegridcell15': 'j_81',
        'mobilebutton2': 'j_83'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_53';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    query_selected = new Tiggr.DataSource(WACPaymentQueryProducts, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_53");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['response', 'product', 'items[0]', 'currency'],
            'ID': 'currency_label',
            'ATTR': '@'
        }, {
            'PATH': ['response', 'product', 'items[0]', 'currency'],
            'ID': '___local_storage___',
            'ATTR': 'WACPaymentitemCurrency'
        }, {
            'PATH': ['response', 'product', 'items[0]', 'description'],
            'ID': '___local_storage___',
            'ATTR': 'WACPaymentitemDescription'
        }, {
            'PATH': ['response', 'product', 'items[0]', 'billing-receipt'],
            'ID': 'billing_label',
            'ATTR': '@'
        }, {
            'PATH': ['response', 'product', 'items[0]', 'item-id'],
            'ID': 'product_id_label',
            'ATTR': '@'
        }, {
            'PATH': ['response', 'product', 'items[0]', 'item-id'],
            'ID': 'product_descr_label',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                var item = itemMap[value];
                return (item && item.hasOwnProperty("name")) ? item.name : "No name";
            }
        }, {
            'PATH': ['response', 'product', 'items[0]', 'item-id'],
            'ID': 'itemImageLarge',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                var item = itemMap[value];
                return (item && item.hasOwnProperty("image")) ? item.image : "";
            }
        }, {
            'PATH': ['response', 'product', 'items[0]', 'price'],
            'ID': 'price_label',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                value = value.toString();
                if (value.indexOf('.') < 0) {
                    value += '.00';
                }
                return '$' + value;
            }
        }, {
            'PATH': ['response', 'product', 'items[0]', 'price'],
            'ID': '___local_storage___',
            'ATTR': 'WACPaymentitemPrice'
        }],
        'requestMapping': [{
            'PATH': ['client_id'],
            'TRANSFORMATION': function(value) {
                return WACPaymentSettings["client_id"]
            }
        }, {
            'PATH': ['timestamp'],
            'ID': '___local_storage___',
            'ATTR': 'WACPaymenttimestamp'
        }, {
            'PATH': ['Authorization'],
            'HEADER': true,
            'TRANSFORMATION': function(value) {
                return "Signature " + generateAuthorizationSignature(WACPaymentSettings["shared_secret"], WACPaymentSettings["application_id"], WACPaymentSettings["developer_name"], localStorage.getItem("WACPaymenttimestamp"));
            }
        }, {
            'PATH': ['product_uri'],
            'ATTR': ' ',
            'TRANSFORMATION': function(value) {
                return WACPaymentSettings["product_uri"];
            }
        }, {
            'PATH': ['item_id'],
            'ID': '___local_storage___',
            'ATTR': 'WACPaymentitemId'
        }, {
            'PATH': ['Accept'],
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['x-source-ip'],
            'HEADER': true,
            'ATTR': ' ',
            'TRANSFORMATION': function(value) {
                return WACPaymentSettings["spoof_ip"];
            }
        }, {
            'PATH': ['application_id'],
            'TRANSFORMATION': function(value) {
                return WACPaymentSettings["application_id"];
            }
        }]
    });
    datasources.push(query_selected);
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_53_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_53';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_79DF_onLoad = j_53_onLoad = function() {
        screen_79DF_elementsExtraJS();
        j_53_windowEvents();
        screen_79DF_elementsEvents();
    }
    // screen window events
    screen_79DF_windowEvents = j_53_windowEvents = function() {
        $('#j_53').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_53').bind({
            pageshow: function() {
                localStorage.setItem('WACPaymentitemDescription', '');
                localStorage.setItem('WACPaymentitemCurrency', '');
                localStorage.setItem('WACPaymentitemPrice', '');
                localStorage.setItem('WACPaymenttimestamp', new Date().getTime());
                try {
                    query_selected.execute({})
                } catch (ex) {
                    console.log(ex.name + '  ' + ex.message);
                    hideSpinner();
                };
            },
        });
    }
    // screen elements extra js
    screen_79DF_elementsExtraJS = j_53_elementsExtraJS = function() {
        // screen (screen-79DF) extra code
    }
    // screen elements handler
    screen_79DF_elementsEvents = j_53_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_56 [name="mobilebutton5"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('WACPaymentAuthorization', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_82 [name="mobilebutton2"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('WACPaymentMain', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_53").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_53_beforeshow();
    });
    if (runBeforeShow) {
        j_53_beforeshow();
    } else {
        j_53_onLoad();
    }
}
$("#j_53").die("pageinit").live("pageinit", function(event, ui) {
    j_53_js();
});